### ISSUE TITLE
No such file or directory: './results/corgi/lora/merge.tmp/unet/diffusion_pytorch_model.bin'

### ISSUE THREAD

**Issue by skymanaditya1** [KU-CVLAB/3DFuse#34]
Hi, I was trying to run your model using both the gradio demo and also using sh run.sh. In both these steps, the code cannot find the path of the unet model in the LoRA finetuning step. 

Here is the stack trace - 

```
Collapsing Lin Lora in out_proj
Traceback (most recent call last):
  File "run_3DFuse.py", line 352, in <module>
    dispatch(SJC_3DFuse)
  File "/home/aditya/Research/phd/code/3DFuse/my/config.py", line 91, in dispatch
    mod.run()
  File "run_3DFuse.py", line 111, in run
    model = getattr(self, family).make()
  File "/home/aditya/Research/phd/code/3DFuse/run_img_sampling.py", line 18, in make
    model = StableDiffusion(**args)
  File "/home/aditya/Research/phd/code/3DFuse/adapt_sd.py", line 135, in __init__
    model=load_3DFuse(self.checkpoint_root(),dir,alpha)
  File "/home/aditya/Research/phd/code/3DFuse/adapt_sd.py", line 122, in load_3DFuse
    state_dict, l = merge("runwayml/stable-diffusion-v1-5",dir,alpha)
  File "/home/aditya/Research/phd/code/3DFuse/adapt_sd.py", line 78, in merge
    state_dict = lora_convert(_tmp_output, as_half=True)
  File "/home/aditya/Research/phd/code/3DFuse/adapt_sd.py", line 33, in lora_convert
    unet_state_dict = torch.load(unet_path, map_location="cpu")
  File "/home/aditya/miniconda3/envs/3DFuse/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/aditya/miniconda3/envs/3DFuse/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/aditya/miniconda3/envs/3DFuse/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './results/corgi/lora/merge.tmp/unet/diffusion_pytorch_model.bin'
```

I think, the code wouldn't also be find the corresponding path inside the vae folder. There are no .bin files created inside the unet and vae folders, just model.safetensors files.

**Comment by skymanaditya1** [comment]
I just realized that I was using the wrong version of diffusers -- which was 0.28.dev, whereas it worked with version 0.15.0. Even though I created a new conda environment, and followed the installation steps, it still installed a version of diffusers that was incompatible with the repository.

**Comment by elegant666yu** [comment]
Hello, how did you solve this problem, I seem to have encountered the same situation. I don't quite understand what you said about the problem of installing the wrong version diffuser, can you tell me in detail how you solved this problem?

**Comment by skymanaditya1** [comment]
You need to install a different version of diffusers library, version 0.15.0 using pip install or however you are installing it.
